### ISSUE TITLE
[1.12.2] [SERVER] Warns about existing world on each startup

### ISSUE THREAD

**Issue by LiskoSlayer63** [delvr/Streams#49]
I created a _new save with the Streams mod_ and every time when I restart my server it does this:

```
[00:23:08] [Server thread/WARN] [FML]: The following Farseek mod(s) can cause issues with existing worlds:

Streams: Can cause unexpected behavior such as incomplete rivers.

It is recommended to make backups of your world before proceeding.

Continue?

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

**Streams version:** 0.4.1
**Farseek version:** 2.2.2
**Forge version:** 14.23.1.2561
**SpongeForge version:** 2555-7.0.0-BETA-2764
**Minecraft version:** 1.12.2

**Comment by delvr** [comment]
Oops, this was supposed to be fixed as per the Farseek 1.12-2.2 changelog. Seems like I hadn't actually ported the change from 1.11. Will fix in the next Farseek release shortly after Christmas. Happy holidays!

**Comment by unstablecraft** [comment]
Was this fixed already  no hurry just asking

**Comment by delvr** [comment]
This is now fixed in Farseek 1.12-2.2.3.

**Comment by armuell** [comment]
I believe this is still occurring on servers with Farseek 1.12-2.2.3 and Steams 0.4.2 @delvr

**Comment by delvr** [comment]
Thanks armuell, I'll take a look.

**Comment by delvr** [comment]
@armuell, I just verified and 2.2.3 is working for me - could you post your server log? Thanks.

**Comment by armuell** [comment]
Sadly I don't have access to the server files. I was reporting on behalf of @unstablecraft as they run the server and they will hopefully upload them soon. Sadly I expect the logs to look very similar to the OP minus some version number changes.

**Comment by LiskoSlayer63** [comment]
Holy s**t, I forgot about this issue after I updated your mod... Yes it has been working all the time after the fix you released! Closing this now..
